### ISSUE TITLE
Execution optimizations still running after turned off

### ISSUE THREAD

**Issue by Davikar** [rgthree/rgthree-comfy#170]
The execution optimizations still seems to be running after I've turned them off in the settings. 
I've been working with the Backend cache nodes (from inspire pack) and this error pops up sometimes after jumping between a few workflows:

```
Exception in thread Thread-14 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "C:\AI\ComfyUI\ComfyUI\main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 209, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 364, in execute
    recursive_output_delete_if_changed(prompt, self.old_prompt, self.outputs, x)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 232, in recursive_output_delete_if_changed
    input_data_all = get_input_data(inputs, class_def, unique_id, outputs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 26, in get_input_data
    obj = outputs[input_unique_id][output_index]
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range
```

Now I'm assuming that if it they were turned off I wouldn't be seeing any rgthree references in this error message?

**Comment by rgthree** [comment]
Not exactly. In order to flip the optimization on/off depending on the user settings, the base execution is always overridden before the decision to apply the optimization or use ComfyUI’s default, unoptimized methods in which case the method is blindly executed passing in the original args as-is.
