### ISSUE TITLE
I'm having issues with the latest version: RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by blueraincoatli** [rgthree/rgthree-comfy#190]
When I queue the prompt, this message will show, and comfyUI will stuck here, I have to restart comfyUI.
I've tried to disable all other custom nodes, just remained rgthree, it didn't work. 
Here is part of console messages:

```
[rgthree] Loaded 37 fantastic nodes.


Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Exception in thread Thread-1 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "E:\ComfyUI_windows_portable\ComfyUI\main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 211, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 211, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 211, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 211, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 989 more times]
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 178, in rgthree_execute
    if get_config_value('features.patch_recursive_execution') is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\py\config.py", line 8, in get_config_value
    return get_dict_value(RGTHREE_CONFIG, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\py\utils.py", line 23, in get_dict_value
    return get_dict_value(found, '.'.join(keys), default)
                                 ^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
got prompt
got prompt
got prompt
got prompt
```

**Comment by rgthree** [comment]
It looks like you have a loop in your workflow, causing ComfyUI to recurse infinitely. This would happen with or without rgthree-comfy.

Check your workflow to ensure your nodes never connect an output to a node that was used previously.

If you don’t think you have a loop,  you can disable the optimization by opening the rgthree-comfy settings (easiest way is right-click the rgthree progress bar at the top of the window and select “settings” from the menu), and deselect the recursion optimization. But, I don’t think that’s it here.

**Comment by rgthree** [comment]
It looks like you’re installing your extensions twice.

This output:

```
Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
```

Should only have one line for each extension, like:
```
Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
```

I think this happened to someone else because they had the `comfyui\custom_nodes` directory in the additional model paths somewhere causing ComfyUI to import everything twice.

Note, this would be bad for all extensions not just rgthree-comfy.

**Comment by blueraincoatli** [comment]
Yes, it's true, it's solved! Thank you very much! I forgot that I've edited the extra_model_paths.yaml
