### ISSUE TITLE
RecursionError: Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by uraniumcrystalsmaster** [rgthree/rgthree-comfy#226]
When I press the generate button, this error pops up. I disabled Optimize ComfyUI's Execution, but it didn't do anything different when the generate button is pressed.

C:\Users\urani\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --force-fp16
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-13 19:55:40.104117
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Users\urani\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\Users\urani\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.6 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16235 MB
xformers version: 0.0.24
Forcing FP16.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
### Loading: ComfyUI-Inspire-Pack (V0.69.4)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2179 [cf6e1efb] | Released on '2024-05-13'
C:\Users\urani\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
OpenPose Editor: Loaded
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected

[rgthree] Loaded 39 epic nodes.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

        "Art is a harmony parallel with nature." - Paul Cézanne

YK Node Suite: Loaded

Import times for custom nodes:
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\Image-Captioning-in-ComfyUI
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\customNodeExample
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\yk-node-suite-comfyui
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ConCarneNode
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-nodes
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-composer
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\DTAIComfyVariables
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.4 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.5 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.6 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR
   1.1 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.3 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   3.2 seconds: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Failed to validate prompt for output 329:
* (prompt):
  - Required input is missing: value
* ConsoleDebug+ 329:
  - Required input is missing: value
Output will be ignored
Failed to validate prompt for output 330:
* (prompt):
  - Required input is missing: value
* ConsoleDebug+ 330:
  - Required input is missing: value
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
Exception in thread Thread-9 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 211, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\execution.py", line 385, in execute
    to_execute = sorted(list(map(lambda a: (len(recursive_will_execute(prompt, self.outputs, a[-1], memo)), a[-1]), to_execute)))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\execution.py", line 385, in <lambda>
    to_execute = sorted(list(map(lambda a: (len(recursive_will_execute(prompt, self.outputs, a[-1], memo)), a[-1]), to_execute)))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 242, in rgthree_recursive_will_execute
    will_execute_value = execution.recursive_will_execute(prompt, outputs, input_unique_id,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 242, in rgthree_recursive_will_execute
    will_execute_value = execution.recursive_will_execute(prompt, outputs, input_unique_id,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 242, in rgthree_recursive_will_execute
    will_execute_value = execution.recursive_will_execute(prompt, outputs, input_unique_id,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 988 more times]
  File "C:\Users\urani\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 225, in rgthree_recursive_will_execute
    will_execute = RgthreePatchRecursiveExecute_Set_patch_recursive_execution_to_false_if_not_working(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

**Comment by uraniumcrystalsmaster** [comment]
There were infinite loops in my ComfyUI workflow, which I figured out how to remove.
