### ISSUE TITLE
error messages when activating / disabling rgthree

### ISSUE THREAD

**Issue by Autantpourmoi** [rgthree/rgthree-comfy#232]
hello since yesterday on a fresh installation of comfyui ( Linux fedora) , if rgthree is enable i've got all those messages , when disable it i'm ok  any idea ?

```
File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error handling request
Traceback (most recent call last):
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/.venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 106, in api_get_loras_info
    api_response = await get_loras_info_response(request, maybe_fetch_metadata=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/rgthree_server.py", line 139, in get_loras_info_response
    info_data = await get_model_info(lora_file,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 42, in get_model_info
    file_path = get_folder_path(file, model_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/rgthree-comfy/py/utils_info.py", line 373, in get_folder_path
    if not os.path.exists(file_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by rgthree** [comment]
Looks like requests being made for the Power Lora Loader for invalid loras; perhaps you moved loras or loaded someone else's workflow (just to check)?

It shouldn't have broken anything, but is annoying. Last commit should have fixed it, please let me know.

**Comment by Autantpourmoi** [comment]
reactivity and efficiency 5/5 , thanks a lot everything seems to be in order . And for the record, my mistake was to change the name of some loras while Comfyui was one and even at restart it'll use by default the last WF with the power lora node with the olrd names in it ...Thank's again
