### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by EnragedAntelope** [rgthree/rgthree-comfy#297]
Hi,
I have randomly started receiving this error at the end of some workflows. The workflow executes fine, and this error never displays in the GUI. It just shows in the console and causes Comfy to completely stop processing anything until I close and restart the console.

If it helps, the workflow I see this most frequently in is an IMG2IMG workflow using Flux. But it is not at all consistent, the workflow can run 10x without issue and the 11th time it will do this for instance. 

Error below:

Exception in thread Thread-20 (prompt_worker):
Traceback (most recent call last):
  File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ComfyUI\main.py", line 121, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "D:\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 217, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 375, in execute
    recursive_output_delete_if_changed(prompt, self.old_prompt, self.outputs, x)
  File "D:\ComfyUI\execution.py", line 237, in recursive_output_delete_if_changed
    input_data_all = get_input_data(inputs, class_def, unique_id, outputs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 27, in get_input_data
    obj = outputs[input_unique_id][output_index]
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by rgthree** [comment]
ComfyUI has just updated the execution flow, so if you've updated now you should see that you are no longer using the rgthree optimization in the terminal on startup.

I'm not sure if that fixes this issue or if that means there's a problem with comfyui in the new execution flow, though. Hopefully it fixes your issue.
