### ISSUE TITLE
When I double-click in an empty area of the workflow and want to bring up the search box, I can't get the mouse click event

### ISSUE THREAD

**Issue by nongyu-gpu** [rgthree/rgthree-comfy#389]
![image](https://github.com/user-attachments/assets/17e7d3a5-6061-45bc-ad4b-a5aa4bcd5cb5)
litegraph.es.js:10058 Uncaught TypeError: this._groups.toReversed is not a function
    at LGraph2.getGroupOnPos (litegraph.es.js:10058:25)
    at LGraphCanvas.processMouseMove (litegraph.es.js:5208:36)
    at LGraphCanvas.processMouseMove (simpleTouchSupport.ts:149:27)
    at LGraphCanvas.processMouseMove (app.ts:1263:35)
getGroupOnPos @ litegraph.es.js:10058
processMouseMove @ litegraph.es.js:5208
LGraphCanvas.processMouseMove @ simpleTouchSupport.ts:149
LGraphCanvas.processMouseMove @ app.ts:1263
4litegraph.es.js:10058 Uncaught TypeError: this._groups.toReversed is not a function
    at LGraph2.getGroupOnPos (litegraph.es.js:10058:25)
    at LGraphCanvas.#processPrimaryButton (litegraph.es.js:4633:27)
    at LGraphCanvas.processMouseDown (litegraph.es.js:4507:12)
    at LGraphCanvas.processMouseDown (changeTracker.ts:276:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:141:27)
    at LGraphCanvas.processMouseDown (rgthree.js:231:48)
    at LGraphCanvas.processMouseDown (app.ts:1235:40)
getGroupOnPos @ litegraph.es.js:10058
#processPrimaryButton @ litegraph.es.js:4633
processMouseDown @ litegraph.es.js:4507
LGraphCanvas.processMouseDown @ changeTracker.ts:276
LGraphCanvas.processMouseDown @ simpleTouchSupport.ts:141
LGraphCanvas.processMouseDown @ rgthree.js:231
LGraphCanvas.processMouseDown @ app.ts:1235
1660litegraph.es.js:10058 Uncaught TypeError: this._groups.toReversed is not a function
    at LGraph2.getGroupOnPos (litegraph.es.js:10058:25)
    at LGraphCanvas.processMouseMove (litegraph.es.js:5208:36)
    at LGraphCanvas.processMouseMove (simpleTouchSupport.ts:149:27)
    at LGraphCanvas.processMouseMove (app.ts:1263:35)
getGroupOnPos @ litegraph.es.js:10058
processMouseMove @ litegraph.es.js:5208
LGraphCanvas.processMouseMove @ simpleTouchSupport.ts:149
LGraphCanvas.processMouseMove @ app.ts:1263
4litegraph.es.js:10058 Uncaught TypeError: this._groups.toReversed is not a function
    at LGraph2.getGroupOnPos (litegraph.es.js:10058:25)
    at LGraphCanvas.#processPrimaryButton (litegraph.es.js:4633:27)
    at LGraphCanvas.processMouseDown (litegraph.es.js:4507:12)
    at LGraphCanvas.processMouseDown (changeTracker.ts:276:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:141:27)
    at LGraphCanvas.processMouseDown (rgthree.js:231:48)
    at LGraphCanvas.processMouseDown (app.ts:1235:40)
getGroupOnPos @ litegraph.es.js:10058
#processPrimaryButton @ litegraph.es.js:4633
processMouseDown @ litegraph.es.js:4507
LGraphCanvas.processMouseDown @ changeTracker.ts:276
LGraphCanvas.processMouseDown @ simpleTouchSupport.ts:141
LGraphCanvas.processMouseDown @ rgthree.js:231
LGraphCanvas.processMouseDown @ app.ts:1235
474litegraph.es.js:10058 Uncaught TypeError: this._groups.toReversed is not a function
    at LGraph2.getGroupOnPos (litegraph.es.js:10058:25)
    at LGraphCanvas.processMouseMove (litegraph.es.js:5208:36)
    at LGraphCanvas.processMouseMove (simpleTouchSupport.ts:149:27)
    at LGraphCanvas.processMouseMove (app.ts:1263:35)
getGroupOnPos @ litegraph.es.js:10058
processMouseMove @ litegraph.es.js:5208
LGraphCanvas.processMouseMove @ simpleTouchSupport.ts:149
LGraphCanvas.processMouseMove @ app.ts:1263
runtime-dom.esm-bundler.js:16 Blocked autofocusing on a <button> element in a cross-origin subframe.
insert @ runtime-dom.esm-bundler.js:16
mountElement @ runtime-core.esm-bundler.js:4672
processElement @ runtime-core.esm-bundler.js:4588
patch @ runtime-core.esm-bundler.js:4456
componentUpdateFn @ runtime-core.esm-bundler.js:5140
run @ reactivity.esm-bundler.js:177
instance.update @ runtime-core.esm-bundler.js:5264
setupRenderEffect @ runtime-core.esm-bundler.js:5274
mountComponent @ runtime-core.esm-bundler.js:5042
processComponent @ runtime-core.esm-bundler.js:4996
patch @ runtime-core.esm-bundler.js:4468
patchKeyedChildren @ runtime-core.esm-bundler.js:5459
patchChildren @ runtime-core.esm-bundler.js:5331
patchElement @ runtime-core.esm-bundler.js:4760
processElement @ runtime-core.esm-bundler.js:4599
patch @ runtime-core.esm-bundler.js:4456
componentUpdateFn @ runtime-core.esm-bundler.js:5220
run @ reactivity.esm-bundler.js:177
instance.update @ runtime-core.esm-bundler.js:5264
callWithErrorHandling @ runtime-core.esm-bundler.js:195
flushJobs @ runtime-core.esm-bundler.js:409
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:319
queueJob @ runtime-core.esm-bundler.js:313
(anonymous) @ runtime-core.esm-bundler.js:5258
resetScheduling @ reactivity.esm-bundler.js:262
trigger @ reactivity.esm-bundler.js:402
set @ reactivity.esm-bundler.js:524
set @ runtime-core.esm-bundler.js:2272
add @ index.mjs:265
onAdd @ index.mjs:280
(anonymous) @ index.mjs:23
emit @ index.mjs:22
add @ index.mjs:8
onReconnecting @ GraphView.vue:126
(anonymous) @ api.ts:157
runtime-dom.esm-bundler.js:16 Blocked autofocusing on a <button> element in a cross-origin subframe.
insert @ runtime-dom.esm-bundler.js:16
mountElement @ runtime-core.esm-bundler.js:4672
processElement @ runtime-core.esm-bundler.js:4588
patch @ runtime-core.esm-bundler.js:4456
componentUpdateFn @ runtime-core.esm-bundler.js:5140
run @ reactivity.esm-bundler.js:177
instance.update @ runtime-core.esm-bundler.js:5264
setupRenderEffect @ runtime-core.esm-bundler.js:5274
mountComponent @ runtime-core.esm-bundler.js:5042
processComponent @ runtime-core.esm-bundler.js:4996
patch @ runtime-core.esm-bundler.js:4468
patchKeyedChildren @ runtime-core.esm-bundler.js:5549
patchChildren @ runtime-core.esm-bundler.js:5331
patchElement @ runtime-core.esm-bundler.js:4760
processElement @ runtime-core.esm-bundler.js:4599
patch @ runtime-core.esm-bundler.js:4456
componentUpdateFn @ runtime-core.esm-bundler.js:5220
run @ reactivity.esm-bundler.js:177
instance.update @ runtime-core.esm-bundler.js:5264
callWithErrorHandling @ runtime-core.esm-bundler.js:195
flushJobs @ runtime-core.esm-bundler.js:409
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:319
queueJob @ runtime-core.esm-bundler.js:313
(anonymous) @ runtime-core.esm-bundler.js:5258
resetScheduling @ reactivity.esm-bundler.js:262
instrumentations.<computed> @ reactivity.esm-bundler.js:435
remove @ index.mjs:272
onRemove @ index.mjs:284
(anonymous) @ index.mjs:23
emit @ index.mjs:22
remove @ index.mjs:11
onReconnected @ GraphView.vue:130
(anonymous) @ api.ts:139
71litegraph.es.js:10058 Uncaught TypeError: this._groups.toReversed is not a function
    at LGraph2.getGroupOnPos (litegraph.es.js:10058:25)
    at LGraphCanvas.processMouseMove (litegraph.es.js:5208:36)
    at LGraphCanvas.processMouseMove (simpleTouchSupport.ts:149:27)
    at LGraphCanvas.processMouseMove (app.ts:1263:35)

**Comment by rgthree** [comment]
This looks like it's an issue in Comfy/Litegraph, not rgthree-comfy. You should file an issue there: https://github.com/Comfy-Org/litegraph.js
