### ISSUE TITLE
 [ERROR] An error occurred while retrieving information for the 'Power Prompt (rgthree)' node.

### ISSUE THREAD

**Issue by bobo522487** [rgthree/rgthree-comfy#399]
[ComfyUI_desktop v0.3.33]

System Info
OS: nt
Python Version: 3.12.4 (main, Jul 25 2024, 21:57:00) [MSC v.1929 64 bit (AMD64)]
Embedded Python: false
Pytorch Version: 2.5.1+cu121

RAM Total
31.91 GB
RAM Free
19.7 GB

```
[2024-12-16 10:39:08.905] [ERROR] An error occurred while retrieving information for the 'Power Prompt (rgthree)' node.
[2024-12-16 10:39:08.905] Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\server.py", line 530, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\ComfyUI\custom_nodes/rgthree-comfy\py\power_prompt.py", line 20, in INPUT_TYPES
    SAVED_PROMPTS_FILES = folder_paths.get_filename_list('saved_prompts')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\folder_paths.py", line 327, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\folder_paths.py", line 288, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'saved_prompts'

[2024-12-16 10:39:08.905] [ERROR] An error occurred while retrieving information for the 'Power Prompt - Simple (rgthree)' node.
[2024-12-16 10:39:08.905] Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\server.py", line 530, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\ComfyUI\custom_nodes/rgthree-comfy\py\power_prompt_simple.py", line 14, in INPUT_TYPES
    SAVED_PROMPTS_FILES=folder_paths.get_filename_list('saved_prompts')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\folder_paths.py", line 327, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\folder_paths.py", line 288, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'saved_prompts'

[2024-12-16 10:39:08.907] [ERROR] An error occurred while retrieving information for the 'SDXL Power Prompt - Positive (rgthree)' node.
[2024-12-16 10:39:08.907] Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\server.py", line 530, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\ComfyUI\custom_nodes/rgthree-comfy\py\sdxl_power_prompt_postive.py", line 23, in INPUT_TYPES
    SAVED_PROMPTS_FILES = folder_paths.get_filename_list('saved_prompts')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\folder_paths.py", line 327, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\folder_paths.py", line 288, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'saved_prompts'

[2024-12-16 10:39:08.907] [ERROR] An error occurred while retrieving information for the 'SDXL Power Prompt - Simple / Negative (rgthree)' node.
[2024-12-16 10:39:08.907] Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\server.py", line 530, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\ComfyUI\custom_nodes/rgthree-comfy\py\sdxl_power_prompt_simple.py", line 24, in INPUT_TYPES
    saved_prompts_files = folder_paths.get_filename_list('saved_prompts')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\folder_paths.py", line 327, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\folder_paths.py", line 288, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'saved_prompts'
```

**Comment by rgthree** [comment]
I can't reproduce this on my machine but, also, this is tied to an old  feature that I don't think anyone even knows about, let alone uses. I've removed it, so the error should go away for you.
