### ISSUE TITLE
KeyError: 'saved_prompts'

### ISSUE THREAD

**Issue by coddz** [rgthree/rgthree-comfy#402]
this issue appears after just updating the rgthree, and I see the new commit about 'saved_prompts'

comfyui python3.10+torch2.3.1+cu121, the messages in console is:

[ERROR] An error occurred while retrieving information for the 'SDXL Power Prompt - Simple / Negative (rgthree)' node.
Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.4\server.py", line 579, in get_object_info
    out[x] = node_info(x)
  File "F:\ComfyUI-aki-v1.4\server.py", line 546, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "F:\ComfyUI-aki-v1.4\custom_nodes\rgthree-comfy\py\sdxl_power_prompt_simple.py", line 24, in INPUT_TYPES
    saved_prompts_files = folder_paths.get_filename_list('saved_prompts')
  File "F:\ComfyUI-aki-v1.4\folder_paths.py", line 334, in get_filename_list
    out = get_filename_list_(folder_name)
  File "F:\ComfyUI-aki-v1.4\folder_paths.py", line 295, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'saved_prompts'

**Comment by 925-Studio** [comment]
Yep, same here.

**Comment by coddz** [comment]
this issue also in comfyui 0.38 python3.12+torch2.5.1+cu124.

Comfyui started completely, and issue appears with the front ui raising.

**Comment by rgthree** [comment]
Oops, forgot a spot. Thanks, should be good with an update.
