### ISSUE TITLE
rgthree-comfy module for custom nodes: glob() got an unexpected keyword argument 'root_dir'

### ISSUE THREAD

**Issue by gateway** [rgthree/rgthree-comfy#49]
Not sure why this is happening, it may be after I installed mtb but I installed a few so it could be anything.. but I wanted to let you know this error is being thrown.

[comfy_mtb] | INFO -> loaded 52 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (3) could not be loaded. This can be ignored, but go to http://none:6006/mtb if you want more information.
Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/rgthree-comfy/__init__.py", line 98, in <module>
    for file in glob.glob('*.py', root_dir=DIR_PY) + glob.glob('*.js', root_dir=os.path.join(DIR_DEV_WEB, 'js')):
TypeError: glob() got an unexpected keyword argument 'root_dir'

Cannot import /notebooks/ComfyUI/custom_nodes/rgthree-comfy module for custom nodes: glob() got an unexpected keyword argument 'root_dir'

I was able to fix this by replacing this line

with this  https://github.com/rgthree/rgthree-comfy/blob/a197b650c3e19e8d4d290944ff571e688a5aca44/__init__.py#L98

for file in glob.glob(os.path.join(DIR_PY, '*.py')) + glob.glob(os.path.join(DIR_DEV_WEB, 'js', '*.js')):

not tested on windows..

**Comment by rgthree** [comment]
Looks like you may be running a version of python older than 3.10 (as that's when `root_dir` was added). If you try updating your python to 3.10, I imagine it should be resolved.

**Comment by rgthree** [comment]
Fixed with [65832bc](https://github.com/rgthree/rgthree-comfy/commit/65832bcc83880e8ad5c57cef04b4754673dba971)
